class OPCEndpoints:
    ACTIVITIES  = "/projects/{project_id}/activities"
    ACTIVITY    = "/projects/{project_id}/activities/{activity_id}"
    WBS         = "/projects/{project_id}/wbs"
    WBS_NODE    = "/projects/{project_id}/wbs/{wbs_id}"
    RELS        = "/projects/{project_id}/activityrelationships"
    REL         = "/projects/{project_id}/activityrelationships/{rel_id}"
    CALENDARS   = "/projects/{project_id}/calendars"
    CALENDAR    = "/projects/{project_id}/calendars/{calendar_id}"
    SCHEDULE    = "/projects/{project_id}/schedule"
    TOKEN       = "/oauth/token"
